name: FastAPI Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI Application
      run: |
        python __main__.py samples/input1.txt samples/input2.txt samples/input3.txt
      
    - name: Upload artifact 1
      uses: actions/upload-artifact@v2
      with:
        name: output_1.txt
        path: samples/input1_output.txt

    - name: Upload artifact 2
      uses: actions/upload-artifact@v2
      with:
        name: output_2.txt
        path: samples/input2_output.txt
    - name: Upload artifact 3
      uses: actions/upload-artifact@v2
      with:
        name: output_3.txt
        path: samples/input3_output.txt